export interface LegalSection {
  title: string;
  content: string;
}

export interface LegalDocument {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
}

export const TERMS_AND_CONDITIONS: Record<'en' | 'ar', LegalDocument> = {
  en: {
    title: "Terms & Conditions",
    lastUpdated: "Last updated: July 2026",
    sections: [
      {
        title: "1. Acceptance of Terms",
        content: "By downloading, accessing, or using the Himam application (\"Himam\", \"App\", or \"Service\"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, you must not access or use the Service. These terms constitute a legally binding agreement between you and Himam."
      },
      {
        title: "2. Eligibility",
        content: "The Service is intended for students and professionals looking to track and advance their career trajectory. By using Himam, you represent and warrant that you have the legal capacity to enter into these Terms under the laws of the Kingdom of Saudi Arabia."
      },
      {
        title: "3. User Accounts",
        content: "To access certain features of Himam, you must register for an account using email/password or supported third-party OAuth providers (Google, Apple). You are responsible for maintaining the confidentiality of your credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account."
      },
      {
        title: "4. User Responsibilities",
        content: "You agree to provide accurate, current, and complete information during registration and onboarding. You must use the App in compliance with all applicable local, national, and international laws, regulations, and executive decrees within the Kingdom of Saudi Arabia."
      },
      {
        title: "5. AI Recommendations Disclaimer",
        content: "Himam utilizes advanced Artificial Intelligence (AI) models (including Google Gemini and OpenAI) to analyze curricula, synthesize memories, and suggest personalized learning tactics. All AI generated content, including coaching responses, suggestions, and focus strategies, is provided \"as-is\" for informational and educational guidance. Himam does not guarantee the absolute accuracy, completeness, or suitability of any AI recommendations."
      },
      {
        title: "6. Learning Plans Disclaimer",
        content: "Personalized study schedules, target milestones, and pacing charts generated by the App are automated educational suggestions designed to help structure user focus. They do not constitute official academic advising, university degree requirements, or guaranteed paths to passing professional examinations. Users are solely responsible for verifying official certification syllabus requirements independently."
      },
      {
        title: "7. Career Recommendation Disclaimer",
        content: "Any career pathways, roadmap tracks, and projected salary trends presented in Himam are market estimates based on educational analytics and public benchmarks. They do not constitute official job offers, guarantees of employment, or financial advising. Actual career trajectories and compensation depend on individual qualifications, market conditions, and employer decisions."
      },
      {
        title: "8. Intellectual Property",
        content: "All content, designs, algorithms, logos, user interfaces, and software code within Himam are the exclusive intellectual property of Himam or its licensors, protected by Saudi copyright laws and international treaties. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the App for personal, non-commercial educational purposes."
      },
      {
        title: "9. Prohibited Conduct",
        content: "You agree not to modify, reverse-engineer, decompile, copy, or distribute any part of the App. You must not attempt to breach security, inject malicious code, exploit API endpoints, or use automated systems (such as bots or scrapers) to extract data from the Service."
      },
      {
        title: "10. Subscription and Payments",
        content: "Certain advanced educational pathways, full-scale roadmaps, or continuous AI coach support may require active premium subscriptions. By enrolling in a subscription, you agree to pay the designated fees and local Value Added Tax (VAT) in accordance with the billing terms of the respective App Store (Apple App Store or Google Play Store)."
      },
      {
        title: "11. Cancellation",
        content: "You can cancel your premium subscription at any time through your mobile device's app store settings. Cancellations will apply to the subsequent billing cycle; previous payments are non-refundable unless required by applicable consumer protection laws."
      },
      {
        title: "12. Limitation of Liability",
        content: "To the maximum extent permitted by the laws of the Kingdom of Saudi Arabia, Himam shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, academic status, data, or career advancement opportunities, arising out of your use of or inability to use the Service."
      },
      {
        title: "13. Account Suspension",
        content: "We reserve the right, without liability and at our absolute discretion, to suspend or terminate your account and restrict your access to Himam if we detect a breach of these Terms, potential security risks, or unauthorized exploitation of the AI Service API."
      },
      {
        title: "14. Changes to Terms",
        content: "We may update these Terms and Conditions from time to time to reflect changes in regulatory standards, product enhancements, or legal requirements. Your continued use of Himam following any updates constitutes acceptance of the modified terms."
      },
      {
        title: "15. Governing Law",
        content: "These Terms and Conditions, and any disputes arising from or relating to them, shall be governed by, and construed in accordance with, the laws of the Kingdom of Saudi Arabia. All legal proceedings shall fall under the exclusive jurisdiction of the competent courts in Riyadh, Saudi Arabia."
      },
      {
        title: "16. Contact Information",
        content: "If you have any questions, concerns, or inquiries regarding these Terms and Conditions, please contact us at support@himam.app."
      }
    ]
  },
  ar: {
    title: "الشروط والأحكام",
    lastUpdated: "آخر تحديث: يوليو 2026",
    sections: [
      {
        title: "1. قبول الشروط",
        content: "بتحميلك، أو تصفحك، أو استخدامك لتطبيق همم (\"همم\" أو \"التطبيق\" أو \"الخدمة\")، فإنك توافق على الالتزام بهذه الشروط والأحكام والتقيد بها. وإذا كنت لا توافق على هذه الشروط، فيجب عليك التوقف فوراً عن استخدام الخدمة. تشكّل هذه الشروط اتفاقية ملزمة قانوناً بينك وبين همم."
      },
      {
        title: "2. الأهلية وشروط الاستخدام",
        content: "تم تصميم هذه الخدمة للطلاب والمهنيين الساعين لتتبع مساراتهم المهنية والنهوض بها. باستخدامك لتطبيق همم، فإنك تقر وتضمن بأن لديك الأهلية القانونية الكاملة للدخول في هذه الاتفاقية والالتزام بها بموجب الأنظمة والقوانين المعمول بها في المملكة العربية السعودية."
      },
      {
        title: "3. الحسابات والمستخدمون",
        content: "للوصول إلى ميزات معينة في تطبيق همم، يتوجب عليك إنشاء حساب مستخدم باستخدام البريد الإلكتروني وكلمة المرور أو عبر معرّفات الهوية للجهات الخارجية المدعومة (Google و Apple). وتتحمل المسؤولية الكاملة عن سرية بيانات اعتمادك وعن كافة الأنشطة التي تتم من خلال حسابك، وتوافق على إخطارنا فوراً بأي استخدام غير مصرح به للحساب."
      },
      {
        title: "4. مسؤوليات المستخدم",
        content: "تتعهد بتقديم معلومات دقيقة، ومحدثة، وكاملة أثناء مرحلة التسجيل وتخصيص البيانات. كما يجب عليك استخدام التطبيق بما يتوافق مع الأنظمة واللوائح والقرارات التنفيذية السارية في المملكة العربية السعودية."
      },
      {
        title: "5. إخلاء مسؤولية توصيات الذكاء الاصطناعي",
        content: "يعتمد تطبيق همم على نماذج ذكاء اصطناعي متطورة (بما في ذلك Google Gemini و OpenAI) لتحليل المناهج واستخلاص الأفكار وتقديم استراتيجيات تركيز مخصصة. تُقدم كافة مخرجات الذكاء الاصطناعي بما في ذلك إجابات الموجه، والمقترحات، وخطط التركيز \"كما هي\" للإرشاد التعليمي والمعرفي فقط. ولا يضمن تطبيق همم دقة هذه التوصيات أو شموليتها أو ملاءمتها الكاملة لقراراتك."
      },
      {
        title: "6. إخلاء مسؤولية الخطط الدراسية",
        content: "تُعد جداول الدراسة والمراحل المخصصة الموصى بها في التطبيق مقترحات تعليمية مؤتمتة لمساعدة المستخدم في تنظيم وقته. وهي لا تمثل بأي حال من الأحوال استشارات أكاديمية رسمية، ولا تغني عن متطلبات الشهادات الجامعية أو متطلبات اجتياز الاختبارات المهنية الرسمية. ويتحمل المستخدم وحده مسؤولية التحقق من متطلبات المناهج الرسمية."
      },
      {
        title: "7. إخلاء مسؤولية التوصيات المهنية والرواتب",
        content: "إن المسارات المهنية وتقديرات الرواتب المعروضة في التطبيق هي مجرد تقديرات مستوحاة من تحليلات سوق العمل ومؤشرات عامة. وهي لا تمثل عروض توظيف رسمية، ولا تضمن الحصول على عمل، كما لا تعد استشارات مالية. تعتمد التطورات الوظيفية الفعلية على مؤهلاتك الفردية وظروف سوق العمل وقرارات جهات التوظيف."
      },
      {
        title: "8. الملكية الفكرية",
        content: "إن كافة المحتويات، والتصاميم، والخوارزميات، والشعارات، وواجهات الاستخدام، والأكواد البرمجية داخل تطبيق همم هي ملكية فكرية حصرية لـ \"همم\" أو الجهات المرخصة لها، وهي محمية بموجب نظام حماية حقوق المؤلف بالمملكة العربية السعودية والاتفاقيات الدولية. يُمنح المستخدم ترخيصاً محدوداً، وغير حصري، وغير قابل للتحويل للاستخدام الشخصي التعليمي غير التجاري."
      },
      {
        title: "9. السلوك المحظور",
        content: "يلتزم المستخدم بعدم تعديل التطبيق، أو فك تشفيره، أو هندسته عكسياً، أو نسخ محتوياته، أو توزيعه. كما يُحظر تماماً محاولة اختراق حماية التطبيق، أو إدخال برمجيات خبيثة، أو استغلال واجهات برمجة التطبيقات، أو استخدام أنظمة آلية (مثل البوتات أو برامج الكشط) لاستخراج البيانات من الخدمة."
      },
      {
        title: "10. الاشتراكات والمدفوعات",
        content: "قد يتطلب الوصول إلى مسارات تعليمية متقدمة، أو خطط طريق متكاملة، أو دعم مستمر وغير محدود من موجه الذكاء الاصطناعي اشتراكاً مدفوعاً. وبالاشتراك، فإنك توافق على دفع الرسوم المحددة وضريبة القيمة المضافة السارية محلياً وفقاً لسياسات وشروط الدفع الخاصة بمتجر التطبيقات المعني (Apple App Store أو Google Play Store)."
      },
      {
        title: "11. إلغاء الاشتراك",
        content: "يمكن للمستخدم إلغاء الاشتراك المدفوع في أي وقت عبر إعدادات الاشتراكات في متجر تطبيقات جهازه المحمول. يسري الإلغاء على دورة الفوترة التالية، وتكون الرسوم المدفوعة سابقاً غير قابلة للاسترداد إلا بموجب ما تنص عليه أنظمة حماية المستهلك السارية."
      },
      {
        title: "12. تحديد المسؤولية",
        content: "إلى الحد الأقصى الذي تسمح به الأنظمة والقوانين السارية في المملكة العربية السعودية، لا يتحمل تطبيق همم أي مسؤولية عن أي أضرار غير مباشرة، أو عرضية، أو خاصة، أو تبعية (بما في ذلك خسارة الأرباح، أو تراجع الأداء الأكاديمي، أو فقدان البيانات، أو تفويت الفرص المهنية) الناتجة عن استخدام الخدمة أو تعذر استخدامها."
      },
      {
        title: "13. تعليق الحساب وإنهاؤه",
        content: "نحتفظ بالحق، بكامل تصرفنا ودون أي مسؤولية، في تعليق حسابك أو إنهائه وتقييد وصولك إلى تطبيق همم إذا تبين لنا انتهاكك لهذه الشروط، أو نشوء مخاطر أمنية محتملة، أو استخدام واجهات الخدمة بصورة غير مصرح بها."
      },
      {
        title: "14. تعديل الشروط",
        content: "يمتلك تطبيق همم الحق في تعديل وتحديث هذه الشروط والأحكام من وقت لآخر لمواكبة التغيرات التنظيمية، أو تحسينات المنتجات، أو المتطلبات القانونية. ويُعد استمرارك في استخدام التطبيق بعد أي تعديل موافقة وقبولاً بالشروط المحدثة."
      },
      {
        title: "15. النظام الواجب التطبيق والاختصاص القضائي",
        content: "تخضع هذه الشروط والأحكام وتُفسر وفقاً لأنظمة وقوانين المملكة العربية السعودية. وتخضع جميع النزاعات الناشئة عنها أو المتعلقة بها للاختصاص القضائي الحصري للمحاكم المختصة في مدينة الرياض، المملكة العربية السعودية."
      },
      {
        title: "16. معلومات الاتصال",
        content: "إذا كان لديك أي استفسار أو تساؤل بخصوص الشروط والأحكام، يرجى التواصل معنا عبر البريد الإلكتروني الرسمي: support@himam.app."
      }
    ]
  }
};

export const PRIVACY_POLICY: Record<'en' | 'ar', LegalDocument> = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: July 2026",
    sections: [
      {
        title: "Introduction",
        content: "Himam (\"we\", \"our\", or \"us\") is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, process, and safeguard your data. This policy is structured to fully comply with the Saudi Personal Data Protection Law (PDPL), GDPR principles where applicable, Apple App Store privacy requirements, and Google Play developer policies."
      },
      {
        title: "Information We Collect",
        content: "We collect several types of data to provide a highly personalized, absolute career engine experience. This includes: \n\n" +
          "• Account Information: Name, username, email address, password, profile avatar, country, and timezone.\n" +
          "• Learning Goals: Learning objectives, target certifications, professional exams, study windows, and milestone progress tracking.\n" +
          "• Career Trajectory Information: Current job, target positions, career goals, target monthly compensation, and skills profile.\n" +
          "• Learning & Performance Tracking: Institution or organization name, stage/year of study, field of study, performance score/GPA, active courses/modules, expected completion targets, and study schedule logs.\n" +
          "• Internship Application History: Records of applications logged (company, role, status pipeline, and notes).\n" +
          "• Capstone Project Metrics: Topics, supervisor details, delivery milestones, and timeline targets.\n" +
          "• Uploaded Documents & Text: Text and metrics processed for exam reviews and study analytics.\n" +
          "• AI Conversations & Metadata: Chat logs and input queries exchanged with the Himam AI Syllabus Coach to personalize focus insights."
      },
      {
        title: "Device and Technical Information",
        content: "To maintain optimal app execution and security, we collect device identifiers, operating system version, browser types, and crash telemetry. We also use strictly necessary cookies to securely maintain session state and authentication tokens."
      },
      {
        title: "How We Use Your Information",
        content: "We process your personal data for clear and legal educational purposes:\n\n" +
          "• Personalized AI Coaching: Powering our Syllabus Coach to provide targeted curriculum tips and study strategies.\n" +
          "• Career Trajectory Generation: Synthesizing customized professional roadmaps matched with public benchmarks.\n" +
          "• Pacing & Analytics Engine: Building real-time progress charts, consistency indexes, and target streak alerts.\n" +
          "• Performance Tracking: Tracking Wrong-Answer journals and calendar milestones."
      },
      {
        title: "Data Storage and Security",
        content: "All personal data is stored securely. Cloud databases and user authentications are managed via Supabase, with robust enterprise-grade AES-256 encryption for data at rest and TLS 1.3 for data in transit. We maintain strict role-based access controls to prevent unauthorized access, loss, or leakage."
      },
      {
        title: "Third-Party Services and AI APIs",
        content: "Himam utilizes OpenAI and Google Gemini APIs server-side to generate career insights, analyze uploaded curriculum topics, and power the conversation engine. All API queries are proxied securely from our backend; your actual API keys or personal credentials are never exposed. These third-party AI engines process inputs strictly as data processors and do not use your personal information to train their base models."
      },
      {
        title: "Your Rights & Data Deletion",
        content: "Under the Saudi Personal Data Protection Law (PDPL) and GDPR, you possess absolute rights regarding your personal data:\n\n" +
          "• Right to Access: Request a copy of all personal data we retain.\n" +
          "• Right to Rectification: Correct inaccurate or incomplete profile details at any time from your settings.\n" +
          "• Right to Erasure (Deletion): Request permanent destruction of your account and all associated cloud-stored records.\n\n" +
          "You can trigger data deletion directly from your account settings, or contact our support team to execute absolute data purging."
      },
      {
        title: "Contact Information",
        content: "For any questions regarding this Privacy Policy, your data rights, or to initiate a formal privacy query, please contact our Data Protection Officer at privacy@himam.app."
      }
    ]
  },
  ar: {
    title: "سياسة الخصوصية",
    lastUpdated: "آخر تحديث: يوليو 2026",
    sections: [
      {
        title: "مقدمة تمهيدية",
        content: "يلتزم تطبيق همم (\"نحن\" أو \"التطبيق\" أو \"المنصة\") بحماية بياناتك الشخصية وخصوصيتك بأقصى درجة. توضح سياسة الخصوصية هذه كيفية جمع البيانات، ومعالجتها، وحمايتها. تم إعداد هذه السياسة وتصميمها لتتوافق بشكل كامل مع نظام حماية البيانات الشخصية السعودي (PDPL)، ومبادئ اللائحة العامة لحماية البيانات (GDPR) عند الاقتضاء، ومتطلبات خصوصية Apple App Store وسياسات مطوري Google Play."
      },
      {
        title: "البيانات التي نقوم بجمعها",
        content: "نقوم بجمع عدة فئات من البيانات لنقدم لك تجربة متميزة ومخصصة بالكامل في تتبع مسارك المهني والدراسي، وتشمل:\n\n" +
          "• معلومات الحساب الأساسية: الاسم الكامل، اسم المستخدم، البريد الإلكتروني، كلمة المرور، الصورة الرمزية، الدولة، والمنطقة الزمنية.\n" +
          "• الأهداف التعليمية: الأهداف الأكاديمية، الشهادات المهنية المستهدفة، مواعيد الاختبارات، فترات الدراسة المفضلة، ومعالم التقدم.\n" +
          "• معلومات المسار المهني: الوظيفة الحالية، الوظائف والرواتب المستهدفة، والمهارات المكتسبة.\n" +
          "• البيانات الأكاديمية والجامعية: اسم الجامعة، التخصص، المعدل التراكمي، الفصل الدراسي، وتاريخ التخرج المتوقع.\n" +
          "• سجل طلبات التدريب: تفاصيل طلبات التدريب التعاوني (الشركة، المسمى الوظيفي، حالة الطلب والملاحظات).\n" +
          "• مشروع التخرج: موضوع البحث، المشرف الأكاديمي، والمخرجات المطلوبة.\n" +
          "• المستندات والنصوص المرفوعة: البيانات التي تقوم بإدخالها أو رفعها لتحليل الأخطاء وحساب التحليلات.\n" +
          "• محادثات واستفسارات الذكاء الاصطناعي: محادثاتك مع الموجه الأكاديمي لتخصيص محتوى التركيز والإرشاد."
      },
      {
        title: "المعلومات التقنية ومعلومات الأجهزة",
        content: "لضمان أداء تقني متميز واستقرار للخدمة، نقوم بجمع معلومات غير مخصصة مثل نوع الجهاز ونظام التشغيل وتفاصيل الأعطال التقنية. كما نستخدم ملفات تعريف الارتباط (Cookies) الضرورية والآمنة لتأكيد هويتك والحفاظ على جلسة تسجيل الدخول آمنة."
      },
      {
        title: "كيفية استخدام بياناتك ومعالجتها",
        content: "نقوم بمعالجة بياناتك لأغراض تعليمية ومهنية واضحة ومشروعة:\n\n" +
          "• تقديم الدعم بالذكاء الاصطناعي: تفعيل موجه المنهج لتقديم نصائح واستراتيجيات دراسية دقيقة.\n" +
          "• صياغة خرائط الطريق المهنية: بناء خرائط طريق مهنية مخصصة ومطابقة لأحدث بيانات سوق العمل بالمملكة.\n" +
          "• محرك التحليلات وقياس التقدم: حساب مستويات الالتزام، سلاسل الدراسة النشطة ومؤشرات الأداء.\n" +
          "• تتبع الأداء الأكاديمي: تشغيل دفتر قيد الأخطاء وجدول الأحداث والامتحانات."
      },
      {
        title: "تخزين البيانات وأمن المعلومات",
        content: "يتم تخزين كافة البيانات بصورة آمنة ومشفرة. وتُدار قواعد البيانات وحسابات المستخدمين عبر خوادم Supabase، مع تفعيل أعلى معايير التشفير (AES-256) لحماية البيانات المخزنة، وبروتوكولات TLS 1.3 لتأمين حركة البيانات. كما نفرض ضوابط صارمة للوصول تمنع التسرب أو الاستخدام غير المصرح به."
      },
      {
        title: "الخدمات الخارجية وواجهات الذكاء الاصطناعي",
        content: "يستخدم تطبيق همم خوادم داخلية آمنة لمعالجة الطلبات عبر OpenAI و Google Gemini. يتم إرسال الاستفسارات عبر خوادمنا الخلفية بطريقة مشفرة ومجهولة الهوية ولا يتم مشاركة أي من بيانات اعتمادك المباشرة مع هذه الجهات. كما أن هذه المحركات لا تستخدم بياناتك لتدريب نماذجها الأساسية."
      },
      {
        title: "حقوقك القانونية وطلب حذف البيانات",
        content: "بموجب نظام حماية البيانات الشخصية السعودي (PDPL)، فإنك تتمتع بحقوق كاملة ومطلقة حيال بياناتك الشخصية:\n\n" +
          "• حق الوصول والمعرفة: طلب نسخة شاملة من بياناتك الشخصية لدينا.\n" +
          "• حق التصحيح: تعديل وتحديث أي بيانات غير دقيقة أو غير مكتملة عبر الإعدادات مباشرة.\n" +
          "• حق الإتلاف والحذف النهائي: طلب مسح حسابك وكافة البيانات المرتبطة به بشكل دائم من الخوادم السحابية.\n\n" +
          "يمكنك تفعيل طلب الحذف النهائي لحسابك مباشرة من إعدادات حسابك بالتطبيق، أو بالتواصل مع فريق الدعم الفني لتنفيذ الطلب فوراً."
      },
      {
        title: "بيانات الاتصال والاستفسارات",
        content: "لأي استفسار يخص سياسة الخصوصية، أو لممارسة حقوقك النظامية بشأن البيانات، يرجى التواصل مع مسؤول حماية البيانات عبر البريد الإلكتروني: privacy@himam.app."
      }
    ]
  }
};

export const COOKIE_POLICY: Record<'en' | 'ar', LegalDocument> = {
  en: {
    title: "Cookie Policy",
    lastUpdated: "Last updated: July 2026",
    sections: [
      {
        title: "1. What Are Cookies",
        content: "Cookies are small text files stored on your device when you load web applications. They are widely used to make applications function more efficiently and securely, as well as to provide analytical insights to system administrators."
      },
      {
        title: "2. How Himam Uses Cookies",
        content: "We use cookies and equivalent browser storage technologies (such as localStorage and sessionStorage) for strictly necessary system purposes:\n\n" +
          "• Session & Authentication: We store encrypted session tokens via Supabase to keep you securely logged in as you navigate between learning tabs.\n" +
          "• Localization Preferences: We save your chosen language (English or Arabic) and regional preferences so the application loads instantly in your preferred format.\n" +
          "• App Theme & UI State: We retain local layout options, sidebar collapse states, and dark mode configuration values."
      },
      {
        title: "3. Third-Party Analytics Cookies",
        content: "We may integrate light analytical tools to measure application stability, load times, and feature usage. These tools use cookies to capture anonymous usage telemetry to help us optimize performance without identifying individual users."
      },
      {
        title: "4. Managing Cookie Settings",
        content: "Most web browsers allow you to manage or disable cookies through their browser preferences. Note that blocking strictly necessary cookies will prevent you from logging in or using the full core capabilities of the Himam career engine."
      }
    ]
  },
  ar: {
    title: "سياسة ملفات تعريف الارتباط",
    lastUpdated: "آخر تحديث: يوليو 2026",
    sections: [
      {
        title: "1. ما هي ملفات تعريف الارتباط (Cookies)",
        content: "ملفات تعريف الارتباط هي ملفات نصية صغيرة تُحفظ على جهازك عند تصفح التطبيقات والمنصات الرقمية. وهي تُستخدم بصورة واسعة لجعل التطبيقات تعمل بكفاءة وأمان أكبر، بالإضافة إلى توفير تحليلات تفاعلية للمشرفين على النظام."
      },
      {
        title: "2. كيف نستخدم ملفات تعريف الارتباط في همم",
        content: "نحن نستخدم ملفات تعريف الارتباط والتقنيات المماثلة في ذاكرة المتصفح المحلية (مثل localStorage و sessionStorage) لأغراض تقنية ضرورية للتشغيل:\n\n" +
          "• الجلسة والتحقق من الهوية: نقوم بحفظ رموز الجلسات المشفرة عبر Supabase لضمان بقاء حسابك متصلاً بشكل آمن أثناء التنقل بين النوافذ والدروس الأكاديمية.\n" +
          "• تفضيلات اللغة والموقع: نحفظ اختيارك المفضل للغة (العربية أو الإنجليزية) لضمان تحميل التطبيق بالشكل الصحيح والمناسب لثقافتك فوراً.\n" +
          "• واجهة وتفضيلات المستخدم: يتم حفظ إعدادات الواجهة المفضلة مثل سمات العرض وحالة القائمة الجانبية لتوفير تجربة مخصصة لك."
      },
      {
        title: "3. ملفات تعريف الارتباط للجهات الخارجية والتحليلية",
        content: "قد نقوم بدمج أدوات تحليلية خفيفة لمتابعة استقرار أداء التطبيق، وأوقات الاستجابة، ومدى فاعلية الميزات الجديدة. تستخدم هذه الأدوات ملفات تعريف الارتباط لجمع بيانات إحصائية مجهولة المصدر تساعدنا على تحسين الخدمة بشكل مستمر دون كشف هوية المستخدم الفردية."
      },
      {
        title: "4. التحكم في إعدادات ملفات تعريف الارتباط",
        content: "تتيح لك معظم متصفحات الإنترنت إمكانية تعطيل أو حظر ملفات تعريف الارتباط عبر قائمة الإعدادات الخاصة بها. يُرجى ملاحظة أن حظر ملفات الارتباط الأساسية قد يعيق عملية تسجيل الدخول أو يمنع الاستفادة الكاملة من الميزات والمسارات التعليمية في تطبيق همم."
      }
    ]
  }
};

export const AI_DISCLAIMER: Record<'en' | 'ar', LegalDocument> = {
  en: {
    title: "AI Usage & Disclaimer",
    lastUpdated: "Last updated: July 2026",
    sections: [
      {
        title: "1. AI Recommendations & Personalized Guidance",
        content: "Himam uses advanced artificial intelligence models (such as Google Gemini) to provide personalized learning plans, exam reviews, career trajectory roadmaps, and continuous productivity suggestions. These features are designed to serve as an interactive mentor to guide and optimize your educational journey."
      },
      {
        title: "2. Informational and Educational Purpose Only",
        content: "All AI-generated insights, recommendations, curriculum suggestions, and coaching dialogues are provided strictly for informational and educational purposes. They do not constitute official academic advising, university degree requirements, professional licensing approvals, career placement guarantees, or financial/legal advice. Users remain fully and solely responsible for their own educational and career decisions."
      },
      {
        title: "3. Technical Limitations & Hallucinations",
        content: "While we employ state-of-the-art guardrails, generative AI models can occasionally generate inaccurate, incomplete, or out-of-date information (commonly referred to as \"hallucinations\"). Himam does not warrant or guarantee the correctness, completeness, or up-to-date nature of any AI recommendation."
      },
      {
        title: "4. User Verification Mandate",
        content: "Users are strongly advised to independently verify all AI-generated curriculum topics, exam patterns, study guides, and certification paths against official institution handbooks or current syllabus guidelines from credentialing bodies (such as local authorities and universities)."
      },
      {
        title: "5. Intellectual Property Rights",
        content: "All AI-generated text and layout configurations are designed to assist user learning. No ownership or copyright is claimed over responses generated dynamically for you; however, the structured UI containers, analytical charts, and underlying prompt pipelines are the exclusive property of Himam."
      }
    ]
  },
  ar: {
    title: "سياسة واستخدام الذكاء الاصطناعي",
    lastUpdated: "آخر تحديث: يوليو 2026",
    sections: [
      {
        title: "1. توصيات الذكاء الاصطناعي والتوجيه الشخصي",
        content: "يستخدم تطبيق همم نماذج ذكاء اصطناعي توليدي متطورة (مثل Google Gemini) لتقديم خطط دراسية مخصصة، ومراجعات للاختبارات، وخرائط طريق للمسارات المهنية، بالإضافة إلى نصائح إنتاجية وتفاعلية مستمرة. تهدف هذه الميزات لتمثيل موجّه رقمي تفاعلي يساعدك في تحسين رحلتك المعرفية."
      },
      {
        title: "2. للأغراض المعرفية والإرشادية فقط",
        content: "تُقدم كافة التحليلات، والتوصيات، ومقترحات المناهج، ومحادثات الموجه الأكاديمي الناتجة عن الذكاء الاصطناعي لأغراض إرشادية وتثقيفية فقط. وهي لا تمثل بأي حال من الأحوال استشارات أكاديمية رسمية، أو بدائل لمتطلبات الجامعات، أو موافقات ترخيص مهنية، أو ضمانات توظيف فعلية، أو استشارات مالية أو قانونية. يظل المستخدم مسؤولاً بشكل كامل ومنفرد عن قراراته التعليمية والمهنية."
      },
      {
        title: "3. الحدود التقنية للنماذج ومخرجات الذكاء الاصطناعي",
        content: "على الرغم من فرضنا لضوابط حماية عالية الجودة، إلا أن نماذج الذكاء الاصطناعي التوليدي قد تقدم أحياناً معلومات غير دقيقة أو غير مكتملة أو قديمة (ما يُعرف بالهلوسة البرمجية). ولا يضمن تطبيق همم دقة أو اكتمال أو تحديث أي معلومات ناتجة عن هذه النماذج تلقائياً."
      },
      {
        title: "4. وجوب التحقق المستقل من المناهج",
        content: "ننصح المستخدمين بشدة بالتحقق المباشر والمستقل من كافة الجداول والمقترحات والشهادات المهنية الموصى بها، ومقارنتها بالأدلة الرسمية المعتمدة من الجامعات أو الهيئات المهنية والترخيصية المعنية (مثل الجهات الحكومية والجامعات المحلية)."
      },
      {
        title: "5. حقوق الملكية الفكرية للمخرجات",
        content: "تُصاغ مخرجات الذكاء الاصطناعي لمساعدتك في عملية التعلّم. لا نطالب بملكية أو حقوق تأليف وحقوق فكرية للمحتوى الذي يتم توليده ديناميكياً خصيصاً لك؛ ومع ذلك، تظل تصاميم الواجهات البرمجية، والرسوم التحليلية، وهياكل الأوامر البرمجية الحافزة ملكية حصرية لتطبيق همم."
      }
    ]
  }
};
